### PR TITLE
Nimony: Default float type should be -1

### PR DESCRIPTION
**Pull request by SirOlaf**

### CODE REVIEW

**Comment by Araq** [comment]
I think in Nim `float` is always mapped to `float64` so `-1` would be an incompatibility.

**Comment by SirOlaf** [comment]
Thought it would be decided by the backend, but it does look like NF at least is mapped to `double`

**Comment by SirOlaf** [comment]
Also for context, literals get assigned -1 so assigning a literal to float32 variable doesn't match https://github.com/nim-lang/nif/blob/master/src/nimony/builtintypes.nim#L39-L40

**Comment by Araq** [comment]
Integers are not floats, `int` is its own type and `float` is merely an alias.

**Comment by SirOlaf** [comment]
I mean like `let x: float32 = 1.0` which currently has mismatched types because literals are -1 and variables get 64, but if it is supposed to be like that the issue is in type checks

**Comment by Araq** [comment]
The type checking is WIP like generics, sets, case statements ... ;-)

**Pull request closed without merging**
